//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseballApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stat
    {
        public int PlayerID { get; set; }
        public string G { get; set; }
        public string AB { get; set; }
        public string R { get; set; }
        public string H { get; set; }
        public string SecondBase { get; set; }
        public string ThirdBase { get; set; }
        public string HR { get; set; }
        public string RBI { get; set; }
        public string BB { get; set; }
        public string K { get; set; }
        public string SB { get; set; }
        public string CS { get; set; }
        public string AVG { get; set; }
        public string SLG { get; set; }
        public string OBP { get; set; }
        public string OPS { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
